name = "campus-valentine-backend"
main = "src/worker.ts"
compatibility_date = "2025-02-01"
keep_vars = true

[triggers]
crons = ["0 0 * * *"] # runs daily at midnight UTC

[[d1_databases]]
binding = "DB"
database_name = "campus-valentine-db"
database_id = "7d550493-b752-4470-94bc-9f19517677de"
